/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/DailyRecommendations` | `/DailyRecommendations`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MyPlaylists` | `/MyPlaylists`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Search` | `/Search`; params?: Router.UnknownInputParams; } | { pathname: `/components/CurrentTrackBar`; params?: Router.UnknownInputParams; } | { pathname: `/components/LoggedInView`; params?: Router.UnknownInputParams; } | { pathname: `/components/NotLoggedInView`; params?: Router.UnknownInputParams; } | { pathname: `/components/test`; params?: Router.UnknownInputParams; } | { pathname: `/hoc/withAuth`; params?: Router.UnknownInputParams; } | { pathname: `/login/QrLogin`; params?: Router.UnknownInputParams; } | { pathname: `/playList/CommentsPage`; params?: Router.UnknownInputParams; } | { pathname: `/playList/MusicPlayer`; params?: Router.UnknownInputParams; } | { pathname: `/playList/PlaylistDetail`; params?: Router.UnknownInputParams; } | { pathname: `/search/SearchResults`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/DailyRecommendations` | `/DailyRecommendations`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/MyPlaylists` | `/MyPlaylists`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Search` | `/Search`; params?: Router.UnknownOutputParams; } | { pathname: `/components/CurrentTrackBar`; params?: Router.UnknownOutputParams; } | { pathname: `/components/LoggedInView`; params?: Router.UnknownOutputParams; } | { pathname: `/components/NotLoggedInView`; params?: Router.UnknownOutputParams; } | { pathname: `/components/test`; params?: Router.UnknownOutputParams; } | { pathname: `/hoc/withAuth`; params?: Router.UnknownOutputParams; } | { pathname: `/login/QrLogin`; params?: Router.UnknownOutputParams; } | { pathname: `/playList/CommentsPage`; params?: Router.UnknownOutputParams; } | { pathname: `/playList/MusicPlayer`; params?: Router.UnknownOutputParams; } | { pathname: `/playList/PlaylistDetail`; params?: Router.UnknownOutputParams; } | { pathname: `/search/SearchResults`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/DailyRecommendations${`?${string}` | `#${string}` | ''}` | `/DailyRecommendations${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/MyPlaylists${`?${string}` | `#${string}` | ''}` | `/MyPlaylists${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Search${`?${string}` | `#${string}` | ''}` | `/Search${`?${string}` | `#${string}` | ''}` | `/components/CurrentTrackBar${`?${string}` | `#${string}` | ''}` | `/components/LoggedInView${`?${string}` | `#${string}` | ''}` | `/components/NotLoggedInView${`?${string}` | `#${string}` | ''}` | `/components/test${`?${string}` | `#${string}` | ''}` | `/hoc/withAuth${`?${string}` | `#${string}` | ''}` | `/login/QrLogin${`?${string}` | `#${string}` | ''}` | `/playList/CommentsPage${`?${string}` | `#${string}` | ''}` | `/playList/MusicPlayer${`?${string}` | `#${string}` | ''}` | `/playList/PlaylistDetail${`?${string}` | `#${string}` | ''}` | `/search/SearchResults${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/DailyRecommendations` | `/DailyRecommendations`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MyPlaylists` | `/MyPlaylists`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Search` | `/Search`; params?: Router.UnknownInputParams; } | { pathname: `/components/CurrentTrackBar`; params?: Router.UnknownInputParams; } | { pathname: `/components/LoggedInView`; params?: Router.UnknownInputParams; } | { pathname: `/components/NotLoggedInView`; params?: Router.UnknownInputParams; } | { pathname: `/components/test`; params?: Router.UnknownInputParams; } | { pathname: `/hoc/withAuth`; params?: Router.UnknownInputParams; } | { pathname: `/login/QrLogin`; params?: Router.UnknownInputParams; } | { pathname: `/playList/CommentsPage`; params?: Router.UnknownInputParams; } | { pathname: `/playList/MusicPlayer`; params?: Router.UnknownInputParams; } | { pathname: `/playList/PlaylistDetail`; params?: Router.UnknownInputParams; } | { pathname: `/search/SearchResults`; params?: Router.UnknownInputParams; };
    }
  }
}
